name: CI

on:
  pull_request:
    branches:
      - main
jobs:
  Jest-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.11.1
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm run test
